---

- name: Information message
  debug:
    msg: Cluster activation will take a while, go grab a coffee :)
  delegate_to: localhost
  run_once: true

- name: Pause for 30 seconds before starting activation
  pause:
    seconds: 30

- name: Run clustering scripts
  command: /bin/bash {{ ignite_bin_dir }}/control.sh --activate --yes
  async: 1000
  poll: 0
  delegate_to: "{{ play_hosts | first }}"
  run_once: true
  when: (persistence.enabled | bool)
  register: init_cluster

- name: Check on cluster initialization
  async_status:
    jid: "{{ init_cluster.ansible_job_id }}"
  register: check_result
  until: check_result.finished
  retries: 30
  delegate_to: "{{ play_hosts | first }}"
  run_once: true
