---

- name: Transfer instance configuration template files to the remote host
  template:
    src: default-config.xml.j2
    dest: "{{ ignite_config_dir }}/default-config.xml"
    owner: "{{ ignite_user }}"
    group: "{{ ignite_group }}"
    mode: "0644"

- name: Create required directories if they dont exist
  file:
    path: "/opt/{{ item }}"
    state: directory
    owner: "{{ ignite_user }}"
    group: "{{ ignite_group }}"
    mode: "0755"
    recurse: yes
  loop:
    - data-persist
    - data-persist
    - data-wal
    - data-wal

- name: Ensure that firewalld configuration is done
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  loop:
    - 48500/tcp
    - 48100/tcp
    - 10800/tcp

- name: Ensure that ignite instance is started
  systemd:
    state: started
    enabled: true
    daemon_reload: true
    name: apache-ignite@default-config.xml

...
