---

- name: Include install_main.yml file conditionally
  include_tasks: install_main.yml
  when: (install_ignite | bool)

- name: Include uninstall_main.yml file
  include_tasks: uninstall_main.yml
  when: not (install_ignite | bool)
